# Generated by Django 2.0.13 on 2020-06-21 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20200620_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='cargo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='peça',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Categoria'),
        ),
        migrations.AlterField(
            model_name='peça',
            name='estado',
            field=models.CharField(choices=[('NOVO', 'NOVO'), ('USADO', 'USADO'), ('DESCARTE', 'DESCARTE')], max_length=8),
        ),
        migrations.AlterField(
            model_name='peça',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Marca'),
        ),
        migrations.AlterField(
            model_name='peça',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Unidade'),
        ),
        migrations.AlterField(
            model_name='trocapecas',
            name='colaborador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.Colaborador'),
        ),
        migrations.AlterField(
            model_name='trocapecas',
            name='dispositivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.Dispositivo'),
        ),
        migrations.AlterField(
            model_name='trocapecas',
            name='peca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.Peça'),
        ),
    ]
