# Generated by Django 2.0.13 on 2020-06-21 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_auto_20200620_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peça',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.Categoria'),
        ),
        migrations.AlterField(
            model_name='peça',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.Marca'),
        ),
        migrations.AlterField(
            model_name='peça',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.Unidade'),
        ),
        migrations.AlterField(
            model_name='trocapecas',
            name='colaborador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.Colaborador'),
        ),
        migrations.AlterField(
            model_name='trocapecas',
            name='dispositivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.Dispositivo'),
        ),
        migrations.AlterField(
            model_name='trocapecas',
            name='peca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.Peça'),
        ),
    ]
